/*!
 * @file
 *
 * @brief テクスチャーフォーマットを提供します。
 *
 * @copyright
 */
#pragma once

enum TEXTURE_FORMAT
{
	TEXTURE_FORMAT_NONE,
	TEXTURE_FORMAT_INDEX4,
	TEXTURE_FORMAT_INDEX8,
	TEXTURE_FORMAT_RGB565,
	TEXTURE_FORMAT_ARGB1555,
	TEXTURE_FORMAT_XRGB1555,
	TEXTURE_FORMAT_ARGB4444,
	TEXTURE_FORMAT_XRGB8888,
	TEXTURE_FORMAT_ARGB8888,
	TEXTURE_FORMAT_DXT1,
	TEXTURE_FORMAT_DXT2,
	TEXTURE_FORMAT_DXT3,
	TEXTURE_FORMAT_DXT4,
	TEXTURE_FORMAT_DXT5,
};

enum MIPMAP
{
	MIPMAP_DEFAULT,		//!< データに依存
	MIPMAP_ENABLE,		//!< 最大数作成
	MIPMAP_DISABLE,		//!< 作成しない
};
